[package]
name = "rustplay"
version = "0.1.0"
edition = "2021"
authors = ["Frans Englich"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
thread-id = "4.2.0"

[[bin]]
name = "rustplay"
path = "src/main.rs"
